/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NumericOperations;
import org.slf4j.*;
import java.util.*;
import operations.*;
import exceptions.*;
public class Library {
	static boolean someLibraryMethod()
	{
		return true;
	}
	public static void main(String[] args) throws  InvalidConstraints  {
		// TODO Auto-generated method stub
	final Logger logger=LoggerFactory.getLogger(Library.class);
  Scanner sc=new Scanner(System.in);
  int i,size;
  logger.info("Application have started");
  try
  {
  logger.info("Inside try block");
  size=sc.nextInt();
  if(size<1||size>20)
  {
  logger.info("InvalidConstraints exception have been thrown");
  throw new InvalidConstraints("Number should be between 1 & 20"); 
  }
  else
  {
    logger.info("Inside try block");
  int depth=sc.nextInt();
  DoubleOperation d=new DoubleOperation();
  Half h=new Half();
  Square s=new Square();
     d.Doubled(size,depth);
	s.Squared(size,depth);
	 h.Halfed(size,depth);
	}
  }
  catch(Exception e)
  {
	  logger.info("Inside catch block");
	  System.out.print(e);
  }
}
}